### 0D Tensor : Scalar
Real world - A single temperature reading from a weather sensor

In [5]:
import torch

temperature = torch.tensor(36.6)

print(temperature)        # tensensor(36.6000)
print(temperature.ndim)   # 0 -> no dimensions, just a single value
print(temperature.shape)  # torch.Size([]) -> empty shape, since it's a scalar value
print(temperature.item())  # 36.6 -> get the Python number from the tensor

tensor(36.6000)
0
torch.Size([])
36.599998474121094


What's happening:
36.6  ← just one number, no rows, no columns, nothing

> Single sensor reading, single loss value after training, single accuracy score — all scalars.

### 1D Tensor : Vector
Real world - One patient's medical report with multiple readings

In [ ]:
patient_record = torch.tensor([98.6, 120.0, 80.0, 95.0])
#                             temp, bp_sys, bp_di, oxygen

print(patient_record)        # tensor([ 98.6000, 120.0000,  80.0000,  95.0000])
print(patient_record.ndim)   # 1 -> one dimension, a list of values
print(patient_record.shape)  # torch.Size([4]) -> 4 values in the tensor
print(patient_record[0])     # tensor(98.6000) -> first value (temperature)
print(patient_record[1])     # tensor(120.0000) -> second value (blood pressure systolic)
print(patient_record[2])     # tensor(80.0000) -> third value (blood pressure diastolic)
print(patient_record[3])     # tensor(95.0000) -> fourth value (oxygen saturation)  

tensor([ 98.6000, 120.0000,  80.0000,  95.0000])
1
torch.Size([4])
tensor(98.6000)
tensor(120.)
tensor(80.)
tensor(95.)


- What's happening:
→ 4 features of ONE patient = 1D tensor of size 4

> One row of a dataset, one word embedding, one feature vector — all 1D tensors.

### 2D Tensor : Matrix
Real world - A small hospital dataset - multiple patients, multiple readings

In [7]:
hospital_data = torch.tensor([
    [98.6, 120.0, 80.0, 95.0],   # patient 1
    [99.1, 130.0, 85.0, 93.0],   # patient 2
    [97.8, 115.0, 75.0, 97.0],   # patient 3
])

print(hospital_data.ndim)   # 2  → rows and columns
print(hospital_data.shape)  # torch.Size([3, 4]) → 3 patients, 4 readings each
print(hospital_data[0])     # tensor([ 98.6000, 120.0000,  80.0000,  95.0000]) → first patient's data
print(hospital_data[1])     # tensor([ 99.1000, 130.0000,  85.0000,  93.0000]) → second patient's data
print(hospital_data[2])     # tensor([ 97.8000, 115.0000,  75.0000,  97.0000]) → third patient's data

2
torch.Size([3, 4])
tensor([ 98.6000, 120.0000,  80.0000,  95.0000])
tensor([ 99.1000, 130.0000,  85.0000,  93.0000])
tensor([ 97.8000, 115.0000,  75.0000,  97.0000])


What's happening : 
→ 3 rows × 4 columns = 2D tensor of shape [3, 4]

> Any tabular dataset, any spreadsheet, weight matrix in neural network — all 2D tensors.

### 3D Tensor : Cube
Real world - A week of hourly stock prices for multiple companies

In [8]:
stock_data = torch.tensor([
    # Day 1: [Apple, Google, Tesla] prices at each hour
    [[180.0, 140.0, 250.0],   # hour 1
     [182.0, 141.0, 253.0],   # hour 2
     [179.0, 139.0, 248.0]],  # hour 3

    # Day 2
    [[183.0, 142.0, 255.0],
     [185.0, 143.0, 258.0],
     [181.0, 140.0, 252.0]],

    # Day 3
    [[178.0, 138.0, 247.0],
     [180.0, 140.0, 250.0],
     [182.0, 141.0, 253.0]],
])

print(stock_data.ndim)   # 3
print(stock_data.shape)  # torch.Size([3, 3, 3])
#                                       ↑  ↑  ↑
#                                     days hrs companies
print(stock_data[0])     # Day 1 data
print(stock_data[1])     # Day 2 data
print(stock_data[2])     # Day 3 data

3
torch.Size([3, 3, 3])
tensor([[180., 140., 250.],
        [182., 141., 253.],
        [179., 139., 248.]])
tensor([[183., 142., 255.],
        [185., 143., 258.],
        [181., 140., 252.]])
tensor([[178., 138., 247.],
        [180., 140., 250.],
        [182., 141., 253.]])


> Time series data, batch of sentences (NLP), sequence data — all 3D tensors.

### 4D Tensor : A stack of 3D Tensors
Real world : A batch of color images fed into a neural network

In [ ]:
# Simulating a batch of 4 color photos (like Instagram photos)
# Each photo: 3 color channels (RGB), 64×64 pixels

batch_photos = torch.rand(4, 3, 64, 64)
#                          ↑  ↑   ↑  ↑
#                        imgs ch  H  W

print(batch_photos.ndim)   # 4
print(batch_photos.shape)  # torch.Size([4, 3, 64, 64])

# Accessing one photo
single_photo = batch_photos[0]
print(single_photo.shape)  # torch.Size([3, 64, 64]) → one image

# Accessing one channel of that photo
red_channel = batch_photos[0][0]
print(red_channel.shape)   # torch.Size([64, 64]) → just red values

## Accessing data inside 4D Tensor

In [10]:
batch = torch.rand(4, 3, 64, 64)

# Get entire image 1
print(batch[0])
# shape → [3, 64, 64]  ← one full color image

# Get RED channel of image 1
print(batch[0][0])
# shape → [64, 64]  ← red pixel grid of image 1

# Get GREEN channel of image 1
print(batch[0][1])
# shape → [64, 64]  ← green pixel grid of image 1

# Get BLUE channel of image 1
print(batch[0][2])
# shape → [64, 64]  ← blue pixel grid of image 1

# Get pixel at row 10, col 20 of RED channel of image 1
print(batch[0][0][10][20])
# shape → scalar  ← single pixel value

tensor([[[0.3150, 0.5323, 0.3430,  ..., 0.8744, 0.9454, 0.5398],
         [0.5812, 0.9167, 0.8208,  ..., 0.8835, 0.0877, 0.6670],
         [0.5669, 0.9772, 0.5145,  ..., 0.4612, 0.0458, 0.4423],
         ...,
         [0.6127, 0.1238, 0.9815,  ..., 0.1618, 0.6335, 0.3995],
         [0.9939, 0.6232, 0.4594,  ..., 0.0951, 0.0529, 0.4294],
         [0.4212, 0.6650, 0.2017,  ..., 0.9212, 0.3700, 0.7465]],

        [[0.0979, 0.0223, 0.1116,  ..., 0.2698, 0.5616, 0.0992],
         [0.8752, 0.4217, 0.8783,  ..., 0.9893, 0.2404, 0.4136],
         [0.5801, 0.0957, 0.8538,  ..., 0.2677, 0.0672, 0.8894],
         ...,
         [0.9126, 0.4545, 0.8621,  ..., 0.6721, 0.7331, 0.2086],
         [0.2067, 0.4304, 0.5128,  ..., 0.0382, 0.9719, 0.8888],
         [0.5432, 0.8625, 0.6405,  ..., 0.3884, 0.0116, 0.5623]],

        [[0.7654, 0.3093, 0.2125,  ..., 0.3354, 0.7778, 0.0968],
         [0.9493, 0.0436, 0.1378,  ..., 0.9976, 0.0301, 0.0601],
         [0.8375, 0.0946, 0.5203,  ..., 0.2822, 0.7072, 0.

### 5D Tensor : Batch  of Videos
Real world - A batch of video clips - like reels being processed by a video model

In [11]:
# 2 video clips
# Each clip: 10 frames, 3 RGB channels, 64×64 pixels

batch_videos = torch.rand(2, 10, 3, 64, 64)
#                          ↑   ↑  ↑   ↑  ↑
#                        vids frm ch   H  W

print(batch_videos.ndim)   # 5
print(batch_videos.shape)  # torch.Size([2, 10, 3, 64, 64])

# Accessing one video
video1 = batch_videos[0]
print(video1.shape)        # torch.Size([10, 3, 64, 64]) → 10 frames

# Accessing one frame of that video
frame1 = batch_videos[0][0]
print(frame1.shape)        # torch.Size([3, 64, 64]) → one frame = one image

# Accessing red channel of that frame
red = batch_videos[0][0][0]
print(red.shape)           # torch.Size([64, 64]) → pixel grid

5
torch.Size([2, 10, 3, 64, 64])
torch.Size([10, 3, 64, 64])
torch.Size([3, 64, 64])
torch.Size([64, 64])


In [12]:
import torch

# 2D — grayscale image
grayscale = torch.rand(64, 64)
print("2D grayscale :", grayscale.shape)      # [64, 64]

# 3D — color image
color_img = torch.rand(3, 64, 64)
print("3D color img :", color_img.shape)      # [3, 64, 64]

# 4D — batch of 4 color images
batch_imgs = torch.rand(4, 3, 64, 64)
print("4D batch imgs:", batch_imgs.shape)     # [4, 3, 64, 64]

# 5D — batch of 2 videos (10 frames each)
batch_vids = torch.rand(2, 10, 3, 64, 64)
print("5D batch vids:", batch_vids.shape)     # [2, 10, 3, 64, 64]

print("\n--- Peeling layers of 5D tensor ---")
print("Full batch    :", batch_vids.shape)            # [2, 10, 3, 64, 64]
print("Video 1       :", batch_vids[0].shape)         # [10, 3, 64, 64]
print("Frame 1       :", batch_vids[0][0].shape)      # [3, 64, 64]
print("Red channel   :", batch_vids[0][0][0].shape)   # [64, 64]
print("One pixel     :", batch_vids[0][0][0][10][20]) # scalar value

2D grayscale : torch.Size([64, 64])
3D color img : torch.Size([3, 64, 64])
4D batch imgs: torch.Size([4, 3, 64, 64])
5D batch vids: torch.Size([2, 10, 3, 64, 64])

--- Peeling layers of 5D tensor ---
Full batch    : torch.Size([2, 10, 3, 64, 64])
Video 1       : torch.Size([10, 3, 64, 64])
Frame 1       : torch.Size([3, 64, 64])
Red channel   : torch.Size([64, 64])
One pixel     : tensor(0.3806)
