In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [5]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
# gender - onehotencoding
# fever - simpleimputer
# cough - ordinalencoder
# city - onehotencoding
# has_covid - labelencoder

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [8]:
print(X_train)

    age  gender  fever   cough       city
85   16  Female  103.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
70   68  Female  101.0  Strong      Delhi
4    65  Female  101.0    Mild     Mumbai
13   64    Male  102.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
0    60    Male  103.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
53   83    Male   98.0    Mild      Delhi
58   23    Male   98.0  Strong     Mumbai

[80 rows x 5 columns]


### 1. Aam Zindagi

In [12]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
print(X_train_fever.shape)
print(X_train_fever)

(80, 1)
[[103.        ]
 [101.04225352]
 [101.        ]
 [101.        ]
 [102.        ]
 [ 99.        ]
 [104.        ]
 [104.        ]
 [101.04225352]
 [102.        ]
 [101.04225352]
 [101.04225352]
 [ 99.        ]
 [ 99.        ]
 [100.        ]
 [ 98.        ]
 [101.        ]
 [102.        ]
 [104.        ]
 [104.        ]
 [102.        ]
 [102.        ]
 [104.        ]
 [ 99.        ]
 [101.04225352]
 [100.        ]
 [101.04225352]
 [103.        ]
 [104.        ]
 [ 98.        ]
 [101.        ]
 [ 98.        ]
 [102.        ]
 [101.        ]
 [100.        ]
 [101.        ]
 [ 98.        ]
 [102.        ]
 [101.04225352]
 [100.        ]
 [ 98.        ]
 [ 98.        ]
 [101.        ]
 [ 99.        ]
 [101.        ]
 [ 98.        ]
 [ 98.        ]
 [101.        ]
 [103.        ]
 [101.        ]
 [103.        ]
 [100.        ]
 [104.        ]
 [ 98.        ]
 [100.        ]
 [104.        ]
 [101.        ]
 [104.        ]
 [101.        ]
 [102.        ]
 [104.        ]
 [104.        ]


In [22]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

print(X_train_cough.shape)
print(X_train_cough)

(80, 1)
[[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]]


In [23]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

print(X_train_gender_city.shape)
print(X_train_gender_city)


(80, 4)
[[0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]
 [

In [24]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

print(X_train_age.shape)
print(X_train_age)

(80, 1)
[[16]
 [79]
 [68]
 [65]
 [64]
 [22]
 [25]
 [51]
 [20]
 [24]
 [75]
 [23]
 [59]
 [14]
 [19]
 [73]
 [51]
 [74]
 [34]
 [42]
 [ 5]
 [82]
 [ 6]
 [49]
 [71]
 [55]
 [34]
 [48]
 [16]
 [ 5]
 [81]
 [24]
 [82]
 [64]
 [13]
 [83]
 [12]
 [49]
 [42]
 [27]
 [69]
 [10]
 [34]
 [72]
 [42]
 [64]
 [40]
 [14]
 [73]
 [15]
 [46]
 [47]
 [44]
 [65]
 [11]
 [12]
 [19]
 [18]
 [49]
 [69]
 [17]
 [54]
 [38]
 [25]
 [70]
 [80]
 [38]
 [ 5]
 [65]
 [31]
 [83]
 [71]
 [69]
 [75]
 [82]
 [60]
 [20]
 [51]
 [83]
 [23]]


In [28]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

### 2.Mentos Zindagi

In [29]:
from sklearn.compose import ColumnTransformer

In [30]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [31]:
transformer.fit_transform(X_train).shape

(80, 7)

In [34]:
transformer.transform(X_test).shape

(20, 7)